#!/usr/bin/env python3
"""Generate local API keys for InfiniMind and optionally write them to .env.

This script generates:
- INFINIMIND_API_KEY
- INFINIMIND_ADMIN_API_KEY

It does not generate OPENAI_API_KEY because that key must be created in your
OpenAI account.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import secrets
import sys
from typing import Iterable

INFINIMIND_KEYS = ("INFINIMIND_API_KEY", "INFINIMIND_ADMIN_API_KEY")



def generate_token(num_bytes: int) -> str:
    """Return a URL-safe random token."""

    return secrets.token_urlsafe(num_bytes)



def read_env_lines(path: pathlib.Path) -> list[str]:
    """Read env file lines if it exists."""

    if path.exists():
        return path.read_text(encoding="utf-8").splitlines(keepends=True)

    return []



def upsert_env_value(lines: list[str], key: str, value: str) -> None:
    """Insert or replace KEY=value within an env file represented as lines."""

    pattern = re.compile(rf"^\s*{re.escape(key)}\s*=")
    for idx, line in enumerate(lines):
        if pattern.match(line):
            lines[idx] = f"{key}={value}\n"
            return

    # Keep file shape predictable when appending new keys.
    if lines and not lines[-1].endswith("\n"):
        lines[-1] = lines[-1] + "\n"
    lines.append(f"{key}={value}\n")



def parse_existing_values(lines: Iterable[str]) -> dict[str, str]:
    """Extract existing key values from env file lines."""

    existing: dict[str, str] = {}
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        existing[key.strip()] = value.strip()
    return existing



def main() -> int:
    """CLI entrypoint."""

    parser = argparse.ArgumentParser(description="Generate InfiniMind API keys")
    parser.add_argument(
        "--env-file",
        default=".env",
        help="Path to env file to update (default: .env)",
    )
    parser.add_argument(
        "--write-env",
        action="store_true",
        help="Write generated keys into the env file",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Regenerate keys even if values already exist in the env file",
    )
    parser.add_argument(
        "--bytes",
        type=int,
        default=32,
        help="Random bytes per generated token (default: 32)",
    )
    parser.add_argument(
        "--shell",
        action="store_true",
        help="Print output as shell exports",
    )
    args = parser.parse_args()

    if args.bytes < 16:
        print("--bytes must be at least 16 for reasonable entropy", file=sys.stderr)
        return 2

    env_path = pathlib.Path(args.env_file).resolve()
    lines = read_env_lines(env_path)
    existing = parse_existing_values(lines)

    values: dict[str, str] = {}
    for key in INFINIMIND_KEYS:
        if not args.force and existing.get(key):
            values[key] = existing[key]
        else:
            values[key] = generate_token(args.bytes)

    if args.write_env:
        for key, value in values.items():
            upsert_env_value(lines, key, value)
        env_path.write_text("".join(lines), encoding="utf-8")

    if args.shell:
        for key, value in values.items():
            print(f"export {key}='{value}'")
    else:
        print("Generated/selected values:")
        for key, value in values.items():
            print(f"  {key}={value}")

    if args.write_env:
        print(f"\nUpdated env file: {env_path}")

    print("\nOPENAI_API_KEY is not generated by this script.")
    print("Create it in your OpenAI account API Keys page:")
    print("  https://platform.openai.com/api-keys")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
